// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlxirteblcjubgvmjebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhseGlydGVibGNqdWJndm1qZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTcxMTMsImV4cCI6MjA3NTMzMzExM30.v6PFjLkIVs0o4fdNMYqf7uTzZ_1yI7t3CO42jKFJxxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});